# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtWidgets

from controlador.archivo import Archivo


class UiMainWindow:
    __control: Archivo

    def __init__(self, control: Archivo):
        self.central_widget = QtWidgets.QWidget()
        self.checkBoxes = []
        self.verticalLayout = QtWidgets.QGridLayout(self.central_widget)
        self.__control = control
        # self.__control.abrir("../controlador/plantillas/PLANTILLA_ICO_2021B.txt")
        self.__control.buscar_materias()
        self.__control.buscar_uas()

        for i in range(self.__control.obtener_num_mat()):
            self.checkBoxes.append(QtWidgets.QCheckBox(self.central_widget))

    def setup_ui(self, window: QtWidgets.QMainWindow):
        window.resize(554, 511)
        row = 0
        col = 0
        for i in range(self.__control.obtener_num_mat()):
            if i == int(len(self.checkBoxes) / 2) * (col + 1):
                col += 1
                row = 0
            self.verticalLayout.addWidget(self.checkBoxes[i], row, col)
            row += 1

        window.setCentralWidget(self.central_widget)

        self.retranslate_ui(window)

    def retranslate_ui(self, window: QtWidgets.QMainWindow):
        uas = self.__control.obtener_uas()
        uas = list(uas)
        uas.sort()
        window.setWindowTitle("Prueba carga de clases")

        for i in range(self.__control.obtener_num_mat()):
            self.checkBoxes[i].setText(uas[i])


if __name__ == "__main__":
    import sys

    ctrl = Archivo()

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow(ctrl)
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
